### ISSUE TITLE
coping installation files memory 

### ISSUE THREAD

**Issue by keroloswilliam** [cvezalis/oracledb-ansible#5]
hi,
i am new to Ansible and i am trying to use this playbook and I get that error 

> TASK [oracle-install : Copy installer files] ***********************************
task path: /home/ubuntu/oracledb-ansible/roles/oracle-install/tasks/main.yml:10
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 96, in run
    item_results = self._run_loop(items)
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 252, in _run_loop
    res = self._execute(variables=task_vars)
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 460, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/copy.py", line 156, in run
    source_full = self._loader.get_real_file(source_full)
  File "/usr/lib/python2.7/dist-packages/ansible/parsing/dataloader.py", line 334, in get_real_file
    data = f.read()
MemoryError
fatal: [oradb]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

I know that is error in ansible  i am posting this error just in case you found solution to that error 

thanks in advance

**Comment by keroloswilliam** [comment]
this issue fixed in the ansible 2.2 devel
